name: Build/release Electron app

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Print version info
        run: |
          bun --version
          node --version
          npm --version
          echo "Electron version: $(bun run electron --version || true)"

      - name: Install Dependencies
        run: bun install --production --frozen-lockfile --prefer-offline --ignore-script

      - name: Install Snapcraft
        # Only install Snapcraft on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo snap install snapcraft --classic

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: bun run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: bun run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: bun run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
