name: Build/release Electron app

on:
  push:
    tags:
      - v1.0.0

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --production --frozen-lockfile --prefer-offline --ignore-scripts

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: bun run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: bun run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: bun run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
