name: Build/release Electron app

on:
  push:
    tags:
      - v1.0.0

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --production --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Install Snapcraft
        if: matrix.os == 'ubuntu-latest'
        run: sudo snap install snapcraft --classic

      - name: Install dependencies for app-builder
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libx11-xcb1 libxcomposite1 libxrandr2 libatk1.0-0 libpangocairo-1.0-0 libgtk-3-0 libxss1

      - name: Fix permissions for app-builder
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x ./node_modules/app-builder-bin/linux/x64/app-builder

      - name: Debug environment (optional)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Node.js version:"
          node -v
          echo "npm version:"
          npm -v
          echo "App-builder binary version:"
          ./node_modules/app-builder-bin/linux/x64/app-builder --version || echo "Failed to get version"
          echo "Environment variables:"
          printenv

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: bun run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: bun run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: bun run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
